# Comment to a new issue.
issueOpened: >
  Hi there! Thank you for taking the time to submit a talk! Speakers like you make the DC tech community awesome — and we’re glad you’re here.

  Rest assured that organizers of quite a few meetups have just been notified of your proposal.

  **Want to target one or two groups specifically?** Mention the group by tagging <code>@dctech/[group]</code> — but please avoid tagging groups at random or tagging more than one or two. Thanks for keeping this group productive and spam-free!

  **Not interested in giving this talk anymore?** Not a problem at all! Thanks for considering it in the first place! Go ahead and close this issue, so we know not to bother you about it.
